[project]
name = "rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.1",
    "torch>=2.7.1",
    "torchrl>=0.9.2",
    "tqdm>=4.67.1",
]
